---
  # Subs to analyse
  SUBREDDITS:
    - Cryptocurrency
    - crypto_currency
    - cryptocurrencies
    - worldnews
  # Number of posts to analyse for each sub
  NUMBER_OF_POSTS: 10
  # Sort by
  SORT_BY: hot
  TRADE_OPTIONS:
    # In your pairing coin
    QUANTITY: 15
    # BTCUSDT will be bought for example
    PAIRING: USDT
    # How often to check for posts and run the script
    # in minutes
    RUN_EVERY: 10
    TEST: True
